#!/bin/bash
export DOCKER_USER_HOME=/home/user
docker run --rm -it \
	-v "$PWD:/work" \
	-v "gradlew_gradle_linux:$DOCKER_USER_HOME/.gradle" \
	-v "gradlew_konan_linux:$DOCKER_USER_HOME/.konan" \
	-v "gradlew_m2:$DOCKER_USER_HOME/.m2" \
	soywiz/kotlin-native-win:java11 \
	./gradlew --no-daemon $*
