#!/bin/bash
export DOCKER_USER_HOME=/home/user/.wine/drive_c/users/user
HOME=`echo ~` docker run --rm -it \
	-v "$PWD:/work" \
	-v "gradlew_gradle_win:$DOCKER_USER_HOME/.gradle" \
	-v "gradlew_konan_win:$DOCKER_USER_HOME/.konan" \
	-v "gradlew_m2:$DOCKER_USER_HOME/.m2" \
	soywiz/kotlin-native-win:java11 \
	wine $*
